name: sakitjantung
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_notification_listener: ^1.3.4
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_slidable: ^3.1.1
  ali_auth: ^1.2.7
  http: ^1.2.2
  animated_bottom_navigation_bar: ^1.3.3
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.0
  firebase_core: ^3.3.0
  fl_chart: ^0.68.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  encrypt: ^5.0.3
  langchain: ^0.7.4
  langchain_community: ^0.3.0
  langchain_openai: ^0.7.0
  dash_chat_2: ^0.0.21
  flutter_dotenv: ^5.1.0

dev_dependencies:
  build_runner: ^2.0.0
  hive_generator: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/birb.svg
    - assets/logo.jpg
    - assets/logo.png
